### ISSUE TITLE
Navigation for modal boxes

### ISSUE THREAD

**Issue by sfuco** [sfuco/sfuco-site#1]
When you click on an image in the exec section, a modal popup comes up that shows their profile. It'd be nice to be able to cycle through the entire set of profiles without having to open/close the popup. This requires structural additions, namely forward and back buttons.

Currently, only the exec section would be affected by this, but if another gallery is implemented in the future, then this would be able to be used there as well.

**Comment by revangel** [comment]
Completed in d37cf6d (2-22-2017)
