### ISSUE TITLE
Vertical navigation on small screens

### ISSUE THREAD

**Issue by sfuco** [sfuco/sfuco-site#2]
On small screens (< ~1050px wide) the vertical navigation begins to overlap with the body.

![image](https://cloud.githubusercontent.com/assets/25047341/22146946/5eacb86e-debb-11e6-81f5-09e7f1e30930.png)

One possibility for a responsive solution would be to implement a toggle (aka hamburger menu) to hide/show the navigation, which in this case would be converted to a full page overlay.

**Comment by revangel** [comment]
Fixed in iteration 16aa9ff (2-22-2017)
