### ISSUE TITLE
Small screen version of contact form

### ISSUE THREAD

**Issue by sfuco** [sfuco/sfuco-site#3]
The contact form looks like this on desktop:

![contact](https://cloud.githubusercontent.com/assets/25047341/22147505/bab3be6c-debd-11e6-8a31-6309c8854ce8.png)

It becomes unusable on small screens since it uses the .modal-box class which has fixed position.

![contact2](https://cloud.githubusercontent.com/assets/25047341/22147565/f85b9ed8-debd-11e6-981f-2b4f265f026e.png)

The small screen version of the contact form should probably be a full screen overlay

**Comment by revangel** [comment]
Working as of commit 60537bf (2-24-2017)
